// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2-IKxRRBfkYkjglAwoI_-bNYPv6tLkw',
    appId: '1:1027749805663:web:02809b213896521397a5ea',
    messagingSenderId: '1027749805663',
    projectId: 'pab1-f197a',
    authDomain: 'pab1-f197a.firebaseapp.com',
    storageBucket: 'pab1-f197a.firebasestorage.app',
    measurementId: 'G-SSLSFNXDWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDov1uAWWXB1FRCg9VanTDX0eslLrqBFTk',
    appId: '1:1027749805663:android:2f0bddb630ed649e97a5ea',
    messagingSenderId: '1027749805663',
    projectId: 'pab1-f197a',
    storageBucket: 'pab1-f197a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxgX5Pd2rH0QEP70jDOaUNSxSzmL5Azs',
    appId: '1:1027749805663:ios:1ba4855e8d34203697a5ea',
    messagingSenderId: '1027749805663',
    projectId: 'pab1-f197a',
    storageBucket: 'pab1-f197a.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxgX5Pd2rH0QEP70jDOaUNSxSzmL5Azs',
    appId: '1:1027749805663:ios:1ba4855e8d34203697a5ea',
    messagingSenderId: '1027749805663',
    projectId: 'pab1-f197a',
    storageBucket: 'pab1-f197a.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD2-IKxRRBfkYkjglAwoI_-bNYPv6tLkw',
    appId: '1:1027749805663:web:9bc5c7bad0cac42c97a5ea',
    messagingSenderId: '1027749805663',
    projectId: 'pab1-f197a',
    authDomain: 'pab1-f197a.firebaseapp.com',
    storageBucket: 'pab1-f197a.firebasestorage.app',
    measurementId: 'G-TEH6EXQ166',
  );
}
